# Site
remote_theme: chriskyfung/amp-affiliately-jekyll-theme

name: "Chris KY FUNG's Page"
title: "Chris KY FUNG's Blog"
description: "Feel free to bookmark this to keep an eye on my project updates"
baseurl: ''
url: https://chriskyfung.github.io
favicon: 'assets/images/favicon_96x96.png'
logo: 'assets/images/logo-plainSVG.svg'
timezone: 'Asia/Hong_Kong'

permalink: /blog/:year/:month/:day/:title
paginate_path: "/blog/page:num/"
paginate: 12

# Navigation features
nav:
  global:
    menu: true

# Content Post-processing
target_blank: false
anchor_link: true

sidebar:
  featured: true
  recent_posts: true
resources_widget: false

# AddThis Inline Share Buttons
addthis: 
  pid: ra-5d01c83d522ad580 # Addthis profile id
  wid: 7kfz # Addthis widget id

# Disqus Comments
amp_disqus: 
  shortname: 'chriskyfung' # Disqus shortname
  url: 'https://chriskyfung.gitlab.io/disqus-amp/' #baseurl of your AMP disqus iframe element
  height: 580

# Google Custom Search Engine ID
cse_id: 011006674894885990812:tjln7k0nyjx 

# Analytics
google_analytics: 'UA-72575541-9' # Google Analytics Tracking ID
gtm: 'GTM-WQMQK3X' # Google Tag Manager ID

# Google Ads
adstyle: true
adsense: 
  client_id: 'ca-pub-4819282024314540' # Google Adsense client ID
  ad_slot:
    sidebar: 1391498756 # Ad Slot that places to sidebar

# Soical Buttons
facebook_id: chriskyfung
pinterest_id: chriskyfung
github_id : chriskyfung
medium_id: chriskyfung

# Buy Me a Coffee
buymeacoffee: chriskyfung

# Copyright Start Year
copyright: 
  prepend: Copyright © 2014-
  ownership: Chris KY FUNG
  link: https://chriskyfung.github.io/

# Authors
authors:
  chris:
    name: Chris KY Fung
    display_name: Chris F.
    gravatar: abd876486b2caa54b43bf64a5a86f620
    email: 
    web: https://en.gravatar.com/chrisfungky
    facebook: https://www.facebook.com/chriskyfung/
    description: "Author of this blog, M.Phil."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-loading-lazy
  - jekyll-gzip
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-scholar

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks: 
    category: '/category/:name/'
    tag: '/tag/:name/'

# Jekyll-Scholar
scholar:
  style: '_bibliography/ieee-without-doi-and-index.csl'
  bibliography: '**/*.bib{,tex}'
  bibliography_template: bib

# Other
markdown: kramdown
highlighter: rouge

jekyll-minifier:
  exclude: 'feed.xml' # Exclude files from processing - file name, glob pattern or array of file names and glob patterns

relative_links:
  enabled: true
  collections: true

# Directories and/or files from the conversion
include: [.github/FUNDING.yml]
exclude: [sync.ffs_db]